#!/bin/sh
set -e

ARGS="$@"
PROG="$1"
shift

while [ "$#" -gt 0 ]; do
	case $1 in
		-h|--host) HOST="$2"; break ;;
		*) shift ;;
	esac
	shift
done

if [ -n "$HOST" ]; then
	if [ ! -f /demo/cert.pem ]; then
		openssl req -x509 -newkey rsa:4096 -keyout /demo/key.pem -out /demo/cert.pem -sha256 -days 3650 -nodes -subj "/CN=$HOST" \
			-addext "subjectAltName=DNS:$HOST,DNS:*.$HOST,IP:127.0.0.1"
	fi
fi

set -- python3 /demo/main.py "$ARGS"

# set an appropriate umask (if one isn't set already)
um="$(umask)"
if [ "$um" = '0022' ]; then
	umask 0077
fi

if service valkey status | grep 'is not running' > /dev/null; then 
	/usr/local/bin/valkey-server /etc/valkey/valkey.conf --daemonize yes
fi

exec $@